# permissions for end users to view devicedrivers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: devicedriver-viewer-role
rules:
- apiGroups:
  - ndd.henderiw.be
  resources:
  - devicedrivers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ndd.henderiw.be
  resources:
  - devicedrivers/status
  verbs:
  - get
