# permissions for end users to view networkdevices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: networkdevice-viewer-role
rules:
- apiGroups:
  - ndd.henderiw.be
  resources:
  - networkdevices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ndd.henderiw.be
  resources:
  - networkdevices/status
  verbs:
  - get
