
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - ndd.henderiw.be
  resources:
  - devicedrivers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ndd.henderiw.be
  resources:
  - networkdevices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ndd.henderiw.be
  resources:
  - networkdevices/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ndd.henderiw.be
  resources:
  - networknodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ndd.henderiw.be
  resources:
  - networknodes/finalizers
  verbs:
  - update
- apiGroups:
  - ndd.henderiw.be
  resources:
  - networknodes/status
  verbs:
  - get
  - patch
  - update
