apiVersion: ndd.henderiw.be/v1
kind: DeviceDriver
metadata:
  name: gnmi-device-driver
  labels:
    ddriver-kind: gnmi
spec:
  container:
    name: gnmi-ddriver
    image: henderiw/netwdevicedriver-gnmi:latest
    imagePullPolicy: Always
    command:
      - /netwdevicedriver-gnmi
    resources:
      requests:
          memory: "64Mi"
          cpu: "30m"
      limits:
        memory: "256Mi"
        cpu: "250m"