---
apiVersion: ndd.henderiw.be/v1
kind: NetworkNode
metadata:
  name: leaf1
  labels:
    target-group: leaf-grp1
spec:
  grpcServer:
    port: 9999
  deviceDriver:
    kind: gnmi
  target:
    address: 172.20.20.5:57400
    credentialsName: srl-secrets
    encoding: json_ietf
    skpVerify: true
